---
- block:
  - name: "[role.domain] gathering facts"
    ansible.builtin.setup:
      gather_subset:
        - env

  - name: "[role.domain] install Active Directory Domain Services"
    ansible.windows.win_feature:
      name: AD-Domain-Services
      include_management_tools: yes
      include_sub_features: yes
      state: present
    register: result
  
  - name: "[role.domain] install domain"
    ansible.windows.win_domain:
      dns_domain_name: '{{ dns_domain_name }}'
      safe_mode_password: '{{ safe_mode_password }}'
    register: ad
  
  - name: "[role.domain] reboot server {{ ansible_facts['hostname'] }}"
    ansible.windows.win_reboot:
      msg: "Installing AD. Rebooting...."
      pre_reboot_delay: 15
    when: ad.changed