---
- hosts: all
  gather_facts: false

- name: "[ansible] provision infrastructure"
  ansible.builtin.import_playbook: "./playbooks/terraform_apply.yml"
  vars:
    debug_enabled: false
    cloud_provider: azure
    workspace: dev
    lab: msdefender
    trusted_ip: "47.184.108.50/32"
    admin_username: "sophosAdmin"
    admin_password: "P@ssw0rd1234!"
    variables:
      enabled: "true"
      name: "defender lab"
      namespace: "microsoft"
      environment: "dev"
      stage: "test"
      location: "eastus"
      address_space: ['10.0.0.0/16']
      subnet_count: 1

- name: "[ansible] configure hosts"
  ansible.builtin.import_playbook: "./playbooks/configure_domain.yml"
  vars:
    domain_admin_username: sophosAdmin
    domain_admin_password: P@ssw0rd1234!
    dns_domain_name: detectionlab.mdr
    safe_mode_password: P@ssw0rd1234!  

  