download_url: https://galaxy.ansible.com/download/cloud-terraform-1.1.1.tar.gz
format_version: 1.0.0
name: terraform
namespace: cloud
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.1
version_url: https://galaxy.ansible.com/api/v2/collections/cloud/terraform/versions/1.1.1/
