---
# Tasks for checkout
- block:
  - name: "[role.git] cloning repository"
    ansible.builtin.git:
      repo: '{{ repo_uri }}'
      dest: '{{ project_path }}'
      key_file: '{{ key_file | default(omit) }}'
      clone: true
    