name: Azure

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        type: choice
        description: Lab to run
        options:
          - microsoft_defender
        required: true
        default: microsoft_defender
permissions:
  id-token: write
  contents: read

env:
  microsoft_defender: willdafoe/terraform-azure-microsoft_defender

jobs:
  which_lab:
    runs-on: ubuntu-latest-8-cores
    outputs:
      project_path: ${{ steps.setvars.outputs.project_path }}
      repo_uri: ${{ steps.setvars.outputs.repo_uri }}
    steps:
      - id: setvars
        run: |
          if [ "${{ github.event.inputs.deployment_name }}" == "microsoft_defender" ]; then
            echo "::set-output name=project_path::${{ github.workspace }}/workspace/${{ github.event.inputs.deployment_name }}"
            echo "::set-output name=repo_uri::${{ env.microsoft_defender }}"
          fi        

  azure_login:
    runs-on: ubuntu-latest
    needs: which_lab
    environment:
      name: ${{ github.event.inputs.environment }}
      url: "https://github.com"
    env:
      repo_uri: ${{ needs.which_lab.outputs.repo_uri }}
      project_path: ${{ needs.which_lab.outputs.project_path }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
  azure_commands:
    runs-on: ubuntu-latest
    needs: azure_login
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - id: azcli
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

