name: Azure

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        type: choice
        description: Lab to run
        options:
          - microsoft_defender
        required: true
        default: microsoft_defender
      environment:
        type: choice
        description: GitHub deployment environment
        options:
          - prod
          - dev
          - qa
          - test
        required: true
        default: prod
permissions:
  id-token: write
  contents: read

env:
  microsoft_defender: willdafoe/terraform-azure-microsoft_defender

jobs:
  which_lab:
    runs-on: ubuntu-latest
    outputs:
      project_path: ${{ steps.setvars.outputs.project_path }}
      repo_uri: ${{ steps.setvars.outputs.repo_uri }}
    steps:
      - id: setvars
        run: |
          if [ "${{ github.event.inputs.deployment_name }}" == "microsoft_defender" ]; then
            echo "::set-output name=project_path::${{ github.workspace }}/workspace/${{ github.event.inputs.deployment_name }}"
            echo "::set-output name=repo_uri::${{ env.microsoft_defender }}"
          fi        

  infra_provision:
    runs-on: ubuntu-latest
    needs: which_lab
    environment:
      name: ${{ github.event.inputs.environment }}
      url: "https://github.com"
    env:
      repo_uri: ${{ needs.which_lab.outputs.repo_uri }}
      project_path: ${{ needs.which_lab.outputs.project_path }}
    steps:
      - name: Checking out ${{ github.repository }}
        id: step1
        uses: actions/checkout@v3
      - name: Checking out repository for ${{ github.event.inputs.deployment_name }}
        id: step2
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repo_uri }}
          path: ${{ env.project_path }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}        
      - name: Login to Azure
        id: step3
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setting up Terraform
        id: tf_setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}          

