name: Azure

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        type: choice
        description: Lab to run
        options:
          - microsoft_defender
        required: true
        default: microsoft_defender
permissions:
  id-token: write
  contents: read

env:
  microsoft_defender: willdafoe/terraform-azure-microsoft_defender

jobs:
  which_lab:
    runs-on: ubuntu-latest
    outputs:
      project_path: ${{ steps.setvars.outputs.project_path }}
      repo_uri: ${{ steps.setvars.outputs.repo_uri }}
    steps:
      - id: setvars
        run: |
          if [ "${{ github.event.inputs.deployment_name }}" == "microsoft_defender" ]; then
            echo "::set-output name=project_path::${{ github.workspace }}/workspace/${{ github.event.inputs.deployment_name }}"
            echo "::set-output name=repo_uri::${{ env.microsoft_defender }}"
          fi        

  terraform_deploy:
    runs-on: ubuntu-latest
    needs: which_lab
    environment:
      name: ${{ github.event.inputs.environment }}
      url: "https://github.com"
    env:
      repo_uri: ${{ needs.which_lab.outputs.repo_uri }}
      project_path: ${{ needs.which_lab.outputs.project_path }}
    steps:
      - id: runner_ip
        run: |
          RUNNER_IP=$(curl https://api.ipify.org)
          if [ "${RUNNER_IP}" ]; then
            echo "runner_ip=${RUNNER_IP}" >>$GITHUB_OUTPUT
          fi
      - id: checkout
        uses: actions/checkout@v3
      - id: checkout_lab
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repo_uri }}
          path: ${{ env.project_path }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - id: setup_terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - id: azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - id: config
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ${{ env.project_path }}/templates/config.yml.j2
          output_file: ${{ env.project_path }}/config/config.yml

