name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        type: choice
        description: Which deployment to run
        options:
          - microsoft_defender
        required: true
        default: microsoft_defender
      trusted_ip:
        type: string
        description: The IP address to whitelist remote access. Must be provided in CIDR notation. 
        required: true
      name:
        type: string
        required: true
        description: A custom name for the deployment label
      namespace:
        type: string
        required: true
        description: A custom namespace for the deployment label
      state:
        type: choice
        description: Equivalent to the terraform command. apply = present, destroy = absent, plan = planned
        options:
          - present
          - planned
          - absent
        required: true
        default: present
      location:
        type: string
        required: true
        description: The Azure region to deploy to
      address_space:
        type: string
        required: true
        description: The address space to use for the virtual network
      admin_username:
        type: string
        required: true
        description: The username for the domain admin account
        default: sophos
      admin_password:
        type: string
        required: true
        description: The password for the domain admin account
      dns_domain_name:
        type: string
        required: true
        description: The DNS domain name to join
        default: sophos.local

jobs:
  deployAnsible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/ansible
        with:
          playbookName: './workspace/playbook.yml'
          requirementsFile: './requirements.yml'
          verbosity: "vvv"
          extraVars: |
            -e deployment_name="${{ github.event.inputs.deployment_name }}" 
            -e trusted_ip="${{ github.event.inputs.trusted_ip }}" 
            -e name="${{ github.event.inputs.name }}" 
            -e namespace="${{ github.event.inputs.namespace }}" 
            -e state="${{ github.event.inputs.state }}" 
            -e location="${{ github.event.inputs.location }}" 
            -e address_space="${{ github.event.inputs.address_space }}" 
            -e admin_username="${{ github.event.inputs.admin_username }}" 
            -e admin_password="${{ github.event.inputs.admin_password }}" 
            -e dns_domain_name="${{ github.event.inputs.dns_domain_name }}" 
  