name: Deploy to Azure

on:
  workflow_dispatch:
    inputs:
      deployment_name:
        type: choice
        description: Which deployment to run
        options:
          - microsoft_defender
        required: true
        default: microsoft_defender
      trusted_ip:
        type: string
        description: The IP address to whitelist remote access. Must be provided in CIDR notation. 
        required: true
        default: 0.0.0.0/0
      name:
        type: string
        required: true
        description: A custom name for the deployment label
        default: github
      environment:
        type: choice
        required: true
        description: The environment to deploy to
        options:
          - dev
          - prod
          - test
          - qa
        default: prod
      location:
        type: string
        required: true
        description: The Azure region to deploy to
        default: eastus
      domain_controller_count:
        type: number
        description: The number of domain controllers to deploy
        required: false
        default: 1
      windows_server_count:
        type: number
        description: The number of Windows servers to deploy
        required: false
        default: 0
      windows_client_count:
        type: number
        description: The number of Windows clients to deploy
        required: false
        default: 1
permissions:
  id-token: write
  contents: read

env:
  microsoft_defender: willdafoe/terraform-azure-microsoft_defender

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      project_path: ${{ steps.setvars.outputs.project_path }}
      repo_uri: ${{ steps.setvars.outputs.repo_uri }}
    steps:
      - name: define lab to deploy
        id: setvars
        run: |
          if [ "${{ github.event.inputs.deployment_name }}" == "microsoft_defender" ]; then
            echo "::set-output name=project_path::${{ github.workspace }}/workspace/${{ github.event.inputs.deployment_name }}"
            echo "::set-output name=repo_uri::${{ env.microsoft_defender }}"
          fi
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      repo_uri: ${{ needs.init.outputs.repo_uri }}
      project_path: ${{ needs.init.outputs.project_path }}
      dns_domain_name: msdefender.lab
      TFE_TOKEN: ${{ secrets.TF_API_TOKEN }}
    needs: init
    steps:
      - name: Checking environment variables
        run: |
          echo repo_uri: ${{ env.repo_uri }} && \
          echo project_path: ${{ env.project_path }} 
      - name: Checkout repository
        uses: actions/checkout@v3   
      - name: Checkout workspace repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.repo_uri }}
          path: ${{ env.project_path }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Jinja2 Action
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: ${{ env.project_path }}/templates/config.yml.j2
          output_file: ${{ env.project_path }}/config/config.yml
          variables: |
            domain_controller_count: ${{ github.event.inputs.domain_controller_count }}
            windows_server_count: ${{ github.event.inputs.windows_server_count }}
            windows_client_count: ${{ github.event.inputs.windows_client_count }}
      - id: config_check
        run: |
          cat ${{ env.project_path }}/config/config.yml
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}    
      - id: init
        working-directory: ${{ env.project_path }}
        run: |
          terraform init
      - id: plan
        working-directory: ${{ env.project_path }}
        run: |
          terraform plan -out terraform.plan -input=false
        env:
          TF_VAR_trusted_ip: ${{ github.event.inputs.trusted_ip }}
          TF_VAR_name: ${{ github.event.inputs.name }}
          TF_VAR_namespace: ${{ env.NAMESPACE }}
          TF_VAR_stage: ${{ env.STAGE }}
          TF_VAR_location: ${{ github.event.inputs.location }}

      #- name: Run Ansible playbook
      #  uses: dawidd6/action-ansible-playbook@v2.6.1
      #  with:
      #    directory: ${{ env.project_path }}/ansible
      #    playbook: playbook.yml
      #    requirements: requirements.yml
      #    options:
      #      --verbose
      #      --extra-vars project_path="${{ env.project_path }}"
      #      --extra-vars deployment_name="${{ github.event.inputs.deployment_name }}"
      #      --extra-vars trusted_ip="${{ github.event.inputs.trusted_ip }}"
      #      --extra-vars name="${{ github.event.inputs.name }}"
      #      --extra-vars namespace="${{ env.NAMESPACE }}"
      #      --extra-vars stage=${{ env.STAGE }}
      #      --extra-vars tf_command="${{ github.event.inputs.terraform_command }}"
      #      --extra-vars location="${{ github.event.inputs.location }}"
      #      --extra-vars address_space="${{ github.event.inputs.address_space }}"
      #      --extra-vars admin_username="${{ github.event.inputs.admin_username }}"
      #      --extra-vars admin_password="${{ github.event.inputs.admin_password }}"
      #      --extra-vars dns_domain_name="${{ github.event.inputs.dns_domain_name }}"
