name: Run ID

on:
  push:

jobs:
  run_id:
    runs-on: ubuntu-latest
    steps:
      - name: Getting most recent artifact details
        id: run
        run: |
          base_uri="https://api.github.com"
          repo="${{ github.repository }}"
          artifacts_uri="$base_uri/repos/$repo/actions/artifacts"
          token="${{ github.token }}"
          api_response=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $token" -H "X-GitHub-Api-Version: 2022-11-28" "$artifacts_uri")
          sorted_artifacts=$(echo "$api_response" | jq --arg name "terraformstatefile" '.artifacts | map(select(.name == $name)) | sort_by(.created_at) | reverse')
          most_recent=$(echo "$sorted_artifacts" | jq -r 'first(.[])')
          RUN_ID=$(echo "$most_recent" | jq -r '.workflow_run.id')
          if [ "$RUN_ID" ]; then
            echo "run_id=${RUN_ID}" >>$GITHUB_OUTPUT
          fi
      - name: Get Run ID
        run: |
          echo "${{ steps.run.outputs.run_id }}"
           

